---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  type: NodePort
  ports:
  - name: http-service
    port: 80
    targetPort: http-pods
    nodePort: 30010
  selector:
    name: induction-hello-world
